[source,bash]
----
$ curl 'http://localhost:8080/api/events/' -i -X POST \
    -H 'Content-Type: application/json;charset=UTF-8' \
    -H 'Accept: application/hal+json' \
    -d '{
  "name" : "Spring",
  "description" : "REST API Development with Spring",
  "beginEnrollmentDateTime" : "2020-06-23T10:09:00",
  "closeEnrollmentDateTime" : "2020-06-24T10:09:00",
  "beginEventDateTime" : "2020-06-25T10:09:00",
  "endEventDateTime" : "2020-06-26T10:09:00",
  "location" : "강남역 D2 스타텁 팩토리",
  "basePrice" : 100,
  "maxPrice" : 200,
  "limitOfEnrollment" : 100
}'
----
[source,http,options="nowrap"]
----
POST /api/events/ HTTP/1.1
Content-Type: application/json;charset=UTF-8
Accept: application/hal+json
Content-Length: 409
Host: localhost:8080

{
  "name" : "Spring",
  "description" : "REST API Development with Spring",
  "beginEnrollmentDateTime" : "2020-06-23T10:09:00",
  "closeEnrollmentDateTime" : "2020-06-24T10:09:00",
  "beginEventDateTime" : "2020-06-25T10:09:00",
  "endEventDateTime" : "2020-06-26T10:09:00",
  "location" : "강남역 D2 스타텁 팩토리",
  "basePrice" : 100,
  "maxPrice" : 200,
  "limitOfEnrollment" : 100
}
----
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Location: http://localhost:8080/api/events/1
Content-Type: application/hal+json
Content-Length: 756

{
  "id" : 1,
  "name" : "Spring",
  "description" : "REST API Development with Spring",
  "beginEnrollmentDateTime" : "2020-06-23T10:09:00",
  "closeEnrollmentDateTime" : "2020-06-24T10:09:00",
  "beginEventDateTime" : "2020-06-25T10:09:00",
  "endEventDateTime" : "2020-06-26T10:09:00",
  "location" : "강남역 D2 스타텁 팩토리",
  "basePrice" : 100,
  "maxPrice" : 200,
  "limitOfEnrollment" : 100,
  "offline" : true,
  "free" : false,
  "eventStatus" : "DRAFT",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/events/1"
    },
    "query-events" : {
      "href" : "http://localhost:8080/api/events"
    },
    "update-event" : {
      "href" : "http://localhost:8080/api/events/1"
    }
  }
}
----
[source,bash]
----
$ echo '{
  "name" : "Spring",
  "description" : "REST API Development with Spring",
  "beginEnrollmentDateTime" : "2020-06-23T10:09:00",
  "closeEnrollmentDateTime" : "2020-06-24T10:09:00",
  "beginEventDateTime" : "2020-06-25T10:09:00",
  "endEventDateTime" : "2020-06-26T10:09:00",
  "location" : "강남역 D2 스타텁 팩토리",
  "basePrice" : 100,
  "maxPrice" : 200,
  "limitOfEnrollment" : 100
}' | http POST 'http://localhost:8080/api/events/' \
    'Content-Type:application/json;charset=UTF-8' \
    'Accept:application/hal+json'
----
|===
|Relation|Description

|`+self+`
|link to self

|`+query-events+`
|link to query events

|`+update-event+`
|link to update and existing events

|===
[source,options="nowrap"]
----
{
  "name" : "Spring",
  "description" : "REST API Development with Spring",
  "beginEnrollmentDateTime" : "2020-06-23T10:09:00",
  "closeEnrollmentDateTime" : "2020-06-24T10:09:00",
  "beginEventDateTime" : "2020-06-25T10:09:00",
  "endEventDateTime" : "2020-06-26T10:09:00",
  "location" : "강남역 D2 스타텁 팩토리",
  "basePrice" : 100,
  "maxPrice" : 200,
  "limitOfEnrollment" : 100
}
----
|===
|Path|Type|Description

|`+name+`
|`+String+`
|Name of new Event

|`+description+`
|`+String+`
|Description of new Event

|`+beginEnrollmentDateTime+`
|`+String+`
|date time to begin of new Event

|`+closeEnrollmentDateTime+`
|`+String+`
|date time to close of new Event

|`+beginEventDateTime+`
|`+String+`
|date time to begin of new Event

|`+endEventDateTime+`
|`+String+`
|date time to end of new Event

|`+location+`
|`+String+`
|location of new Event

|`+basePrice+`
|`+Number+`
|base price of new Event

|`+maxPrice+`
|`+Number+`
|max price of new Event

|`+limitOfEnrollment+`
|`+Number+`
|limit of enrollment of new Event

|===
|===
|Name|Description

|`+Accept+`
|accept header

|`+Content-Type+`
|content type header

|===
[source,options="nowrap"]
----
{
  "id" : 1,
  "name" : "Spring",
  "description" : "REST API Development with Spring",
  "beginEnrollmentDateTime" : "2020-06-23T10:09:00",
  "closeEnrollmentDateTime" : "2020-06-24T10:09:00",
  "beginEventDateTime" : "2020-06-25T10:09:00",
  "endEventDateTime" : "2020-06-26T10:09:00",
  "location" : "강남역 D2 스타텁 팩토리",
  "basePrice" : 100,
  "maxPrice" : 200,
  "limitOfEnrollment" : 100,
  "offline" : true,
  "free" : false,
  "eventStatus" : "DRAFT",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/events/1"
    },
    "query-events" : {
      "href" : "http://localhost:8080/api/events"
    },
    "update-event" : {
      "href" : "http://localhost:8080/api/events/1"
    }
  }
}
----
|===
|Path|Type|Description

|`+id+`
|`+Number+`
|identifier of new Event

|`+name+`
|`+String+`
|Name of new Event

|`+description+`
|`+String+`
|Description of new Event

|`+beginEnrollmentDateTime+`
|`+String+`
|date time to begin of new Event

|`+closeEnrollmentDateTime+`
|`+String+`
|date time to close of new Event

|`+beginEventDateTime+`
|`+String+`
|date time to begin of new Event

|`+endEventDateTime+`
|`+String+`
|date time to end of new Event

|`+location+`
|`+String+`
|location of new Event

|`+basePrice+`
|`+Number+`
|base price of new Event

|`+maxPrice+`
|`+Number+`
|max price of new Event

|`+limitOfEnrollment+`
|`+Number+`
|limit of enrollment of new Event

|`+free+`
|`+Boolean+`
|it tells is this event is free or not

|`+offline+`
|`+Boolean+`
|it tells is this event is offline or not

|`+eventStatus+`
|`+String+`
|event status

|`+eventStatus+`
|`+String+`
|event status

|===
|===
|Name|Description

|`+Location+`
|Location header

|`+Content-Type+`
|content-type

|===